### ISSUE TITLE
Question about the details of the decoder

### ISSUE THREAD

**Issue by Zhanyuan23333** [nv-tlabs/nglod#17]
HI, thanks for your excellent work! Your paper describes that the decoder occupies 90KB, but I can't find the corresponding implementation in the code. Can you tell me the details of the decoder? For example, which parts are included, thank you very much!

**Comment by tovacinni** [comment]
Hi, thanks for your interest in our work!

The decoder is defined in https://github.com/nv-tlabs/nglod/blob/main/sdf-net/lib/models/OctreeSDF.py in `self.louts`. The 90KB calculation comes from `feature_dim * hidden_dim + hidden_dim * 4 bytes` (i.e. the uncompressed floating point representation to store the network weights) for a single decoder of about ~17KB and since we have 5 if you have 5 LODs the total comes out to be 90KB.

Let me know if this doesn't make sense. Thanks!

**Comment by Zhanyuan23333** [comment]
I found that the storage of LOD1 in the paper is 96kb, so is the decoder of LOD1 also 90kb?

**Comment by tovacinni** [comment]
The decoder of all layers are defined & initialized the same way.
